### PR TITLE
feat: ignore .gitignore files and folders

### PR DESCRIPTION
**Pull request by nunomaduro**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes

This feature makes PHP Insights automatically obey `.gitignore` and ignore files based on rules listed there.

Is a new feature and also we are bumping a new dependency - so it's a minor version.

### CODE REVIEW

**Comment by nunomaduro** [comment]
Do you guys know why we are getting this error? 
```RuntimeException: The "ignoreVCSIgnored" option cannot be used by the Finder as the "/home/travis/build/[secure]/phpinsights/tests/Infrastructure/Repositories/../../Fixtures/Tree/.gitignore" file is not readable.```

**Comment by olivernybroe** [comment]
> Do you guys know why we are getting this error?
> `RuntimeException: The "ignoreVCSIgnored" option cannot be used by the Finder as the "/home/travis/build/[secure]/phpinsights/tests/Infrastructure/Repositories/../../Fixtures/Tree/.gitignore" file is not readable.`

Hmm sounds like a permission error.

**Comment by shrink** [comment]
@olivernybroe @nunomaduro Do we know if this feature will be added? Anything I can do to help this be merged? Thank you :-)

**Comment by olivernybroe** [comment]
@shrink It's something we don't mind at all adding. 

This PR is kinda all though :) 

if you are up for it, you can create a new pr with this feature with passing tests and we can get it merged into next major version

**Comment by shrink** [comment]
@olivernybroe great, thank you! I will do that today :)

**Comment by nunomaduro** [comment]
No plans on working on this at the moment.

**Pull request closed without merging**
