### PR TITLE
Fix/run tests on macos

### PR DESCRIPTION
**Pull request by akosglue**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Fixed tickets | #... 

I tried to run all tests on a Mac but 1 test is marked as skipped and with this PR we can run all tests on a Mac.

### CODE REVIEW

**Comment by akosglue** [comment]
Well, the failing check is not related to the commits but what is supposed to happen to the failing check? Is that something to take care of in this PR?

**Comment by 50bhan** [comment]
@akosglue Yes, because apparanetly the signature of `InputOption` has been changed from `string|string[]|int|bool|null` to `string|string[]|bool|null`.

**Comment by nunomaduro** [comment]
@50bhan Can this be merged?

**Comment by 50bhan** [comment]
@nunomaduro Yes, the code is fine and we can merge it.

@akosglue I think it's better to revert the merging of #472 into your PR. And then after we merged #472 into Master, you can rebase your branch and your tests will pass.

**Comment by akosglue** [comment]
Now we are back where it was, 1 failing check. After merge of #472 I will do the necessary and this PR will also pass.

**Review by Jibbarth — APPROVED** [review]
Thank you for improving this @akosglue :+1: 

I just merged #472, can you rebase to get all check green ?

**Review by Jibbarth — APPROVED** [review]
LGTM :+1:

**Pull request merged**
