### PR TITLE
Added Change Log to the website

### PR DESCRIPTION
**Pull request by krisnaw**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| Fixed tickets | #107 

Hi guys, 🙏🏽apologies for the delay
I've added new page for Change Log that can be accessed from the navigation menu and docs

### CODE REVIEW

**Comment by olivernybroe** [comment]
@krisnaw nice to see a pr for this! 

Would it be possible to get the changelog which is stored in the root of the project so we don't have to update two changelogs each time? :)

**Comment by krisnaw** [comment]
Hi @olivernybroe let me try if that possible

**Comment by krisnaw** [comment]
Hi @olivernybroe do you have any advise? I've tried to point out the Changelog, but I think VuePress can't access the files outside the root directory. 
I was thinking if possible to copy the Change log to Vuepress directory during the Travis CLI build

**Comment by Jibbarth** [comment]
@krisnaw Thanks for working on this. 

As far I know, it's not Travis which deploy the docs. (https://github.com/nunomaduro/phpinsights/blob/master/.travis.yml) 

Did you try with symbolic link ? Or may the changelog page can grab the CHANGELOG.md content ?

@nunomaduro What your thought about this ? How the doc is deployed ?

**Comment by nunomaduro** [comment]
`symbolic link` maybe a good idea. Let's try it.

**Comment by krisnaw** [comment]
Hi guys, thanks for the advice 

I've tried using `symbolic link` but no luck, it seems the web pack won't read the files. 
I've tried [this solution](https://github.com/webpack/webpack/issues/1643) as well 

Step to reproduce
1. From outside phpinsight directory, `ln -s phpinsights/CHANGELOG.md phpinsights/docs/`
2. run `yarn run vuepress dev`

**Comment by nunomaduro** [comment]
Hummmm, How about a composer post install/update that copy/pasts the changelog in that folder? And we can also use `.gitignore` to ignore the copy pasted file.

**Comment by olivernybroe** [comment]
What if you make the symbolic link in the other direction, so the root edition of the changelog is actually a symbolic link?

**Comment by olivernybroe** [comment]
Another solution is to do like vuepress own documentation does and have hyperlink to the `.md` file. That's a quick and easy solution, however not as pretty as having it actually in the docs.

**Comment by krisnaw** [comment]
So I've tried @nunomaduro advice by adding scripts like to the composer and its works. 
```
        "post-root-package-install": [
            "@php -r \"copy('CHANGELOG.md', 'docs/CHANGELOG.md');\""
        ]
```

**Comment by nunomaduro** [comment]
@krisnaw Great, can you update the pull request?

**Comment by nunomaduro** [comment]
Thank you for this.

**Pull request merged**
