### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by xuanquynh**
This pull request removes some current unused imports.

### CODE REVIEW

**Comment by xuanquynh** [comment]
Well. I just take a look at the code to have an overview and found that there aren't any tests.

**Comment by szepeviktor** [comment]
@xuanquynh Excuse me.

We use PHPStan: https://github.com/nunomaduro/phpinsights/blob/feat/first/phpstan.neon.dist

**Comment by szepeviktor** [comment]
Just issue `vendor/bin/phpstan analyze`

**Comment by xuanquynh** [comment]
@szepeviktor Thank you! I I mean I didn't see any tests inside the tests directory. :)

**Pull request merged**
