### PR TITLE
Feature/php8 and GitHub action

### PR DESCRIPTION
**Pull request by Jibbarth**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Fixed tickets | #... 

Hey :wave: 

This is a reopen PR, following #444. I hope that pushing my branch on the repository directly will trigger github Action... 

Let's see !

### CODE REVIEW

**Review by olivernybroe — APPROVED** [review]
Awesome!

**Comment by Synchro** [comment]
Any chance of giving this a kick so it can be merged? The tests have passed but travis has stalled, probably just needs retriggering.

**Comment by mwi-gofore** [comment]
> Any chance of giving this a kick so it can be merged? The tests have passed but travis has stalled, probably just needs retriggering.

Travis configuration was deleted in this PR, so naturally it won't trigger :)

**Comment by shrink** [comment]
Per the `required` label, someone with administrator permissions will need to remove the `continuous-integration/travis-ci` check.

@nunomaduro if you have a moment, are you able to action this? The steps are: Settings > [Branches](https://github.com/nunomaduro/phpinsights/settings/branches) > `master` > Require status checks to pass before merging > uncheck `continuous-integration/travis-ci` -> save

Then this PR will be mergeable -- thanks!

**Comment by nunomaduro** [comment]
Done. @shrink

**Comment by Jibbarth** [comment]
Oh, great ! 

Thank you @nunomaduro and thank you @shrink for providing steps :muscle: 

Let's merge this :rocket:

**Pull request merged**
