### PR TITLE
Insight on ourselves

### PR DESCRIPTION
**Pull request by szepeviktor**
Related to #24

### CODE REVIEW

**Comment by nunomaduro** [comment]
At the moment we don't have exit code 🤥.

It's a good proposal, but first we need to develop the exit code on php insights, than we can have this.

**Comment by szepeviktor** [comment]
@nunomaduro This PR is an inspiration for you!

**Comment by szepeviktor** [comment]
Have you seen

> Use of undefined constant PHP_CODESNIFFER_CBF

?

**Comment by nunomaduro** [comment]
What is the context? here? @szepeviktor

**Comment by szepeviktor** [comment]
This PR: https://travis-ci.org/nunomaduro/phpinsights/jobs/532407909#L574

**Comment by nunomaduro** [comment]
Fixed https://github.com/nunomaduro/phpinsights/commit/f68e13a26770aa1984415ed848947177ff9939cd.

**Comment by szepeviktor** [comment]
Thanks.

**Pull request closed without merging**
