### PR TITLE
Allow psr/simple-cache ^2.0 and ^3.0

### PR DESCRIPTION
**Pull request by bastien-phi**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| Fixed tickets | #522 #573 

Allows installation of `psr/simple-cache` in versions `^2.0` and `^3.0`

### CODE REVIEW

**Comment by bastien-phi** [comment]
I had to exclude `psr/simple-cache:^3.0` from `symfony:^4.4` build because the `composer.json` of `symfony/cache` allows installation of `psr/simple-cache:^1.0|^2.0|^3.0` but using version `^3.0` causes `LogicException` saying that the version of `symfony/cache` is not compatible with `psr/simple-cache:^3.0` (see https://github.com/nunomaduro/phpinsights/runs/6523949630?check_suite_focus=true#step:9:9)

**Comment by cmgmyr** [comment]
I noticed that Laravel 9 wasn't in the test suite, so I added it here: #581. Once my PR is merged, let's make sure this PR runs the updated test suite successfully. cc: @JustSteveKing

**Comment by JustSteveKing** [comment]
Good call!

**Comment by bastien-phi** [comment]
@cmgmyr ping me when you PR is merged. I will rebase this one after that

**Comment by JustSteveKing** [comment]
> @cmgmyr ping me when you PR is merged. I will rebase this one after that

@bastien-phi this is now merged!

**Comment by bastien-phi** [comment]
AFK, I couldn't rebate from my phone 😅 Hope that a merge is not a problem

**Comment by cmgmyr** [comment]
Thanks @bastien-phi looks great, thanks for the contribution!

**Pull request merged**
