### PR TITLE
Add support for sebastian/diff 6.0

### PR DESCRIPTION
**Pull request by IsraelPinheiro**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Fixed tickets | #678 #676 #693

Add support to the newest sebastian/diff version

### CODE REVIEW

**Comment by RSickenberg** [comment]
@nunomaduro Please merge :)

**Comment by leonardyrj** [comment]
wip

**Comment by brandonferens** [comment]
Any word or progress on this? This issue is holding up my ability to upgrade to Pest v3. At the moment it isn't possible to run Pest v3, Insights, and PHPunit 11 together because of conflicting `sebastian/diff` versions.

**Comment by Sergiobop** [comment]
Sadly, despite being an amazing package, it is kinda abandoned

Anything we can do to help here? I think this PR is very simple and should be easy to merge

**Comment by brandonferens** [comment]
Agreed @Sergiobop. 

@cmgmyr, @Jibbarth, or @JustSteveKing has this project been abandoned? I like this package but understand if it has come to the end of life. I would just like to know how to proceed. Thanks!

**Comment by Jibbarth** [comment]
Hi all ! 

Sorry for the delay :sweat:, but thanks for the ping :) 

Let's merge it and let me check to see if there is any other dependencies that can be updated.

**Comment by ond-danny** [comment]
@IsraelPinheiro @Jibbarth 

When will this be available as a release? I notice it's been merged but release is still at v2.11 back last year.

We have upgraded to Laravel 11 but this incompatibility is holding back upgrade of phpunit. Since upgrade out test packages don't execute properly so I'd like to get phpunit and insights updated.

**Comment by elnur-ibr** [comment]
That issue holding us back to upgrade phpunit. Does anyone know when it could be released?

**Comment by cmgmyr** [comment]
@elnur-ibr just tagged `v2.12.0`

**Comment by brandonferens** [comment]
Thanks! I'm back up and running with Insights!

**Comment by ond-danny** [comment]
Wonderful thanks for this :)

**Comment by girardotcl** [comment]
Thank you so much ! 🙏🏼

**Pull request merged**
