### PR TITLE
Add exit status code error when detect Security Issues

### PR DESCRIPTION
**Pull request by Jibbarth**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Fixed tickets | N/A

I think when security issues are detected, we should in every case return an exit error code

### CODE REVIEW

**Comment by nunomaduro** [comment]
Thanks!

**Comment by nunomaduro** [comment]
@Jibbarth Can you make this optional as like other `min` options? And also update the docs?

**Comment by Jibbarth** [comment]
In effect, the travis build fail with composer `prefer-lowest` flag :sweat:  

What do you want in option ? `--disable-security-check` ? I think it should be enabled by default, WDYT ?

**Comment by nunomaduro** [comment]
Sounds good: Make it explicit.

**Pull request merged**
