### PR TITLE
Added new logo to readme file

### PR DESCRIPTION
**Pull request by rahman95**
| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | No
| Fixed tickets | N/A

Added logo from this [Nunos' Tweet](https://twitter.com/enunomaduro/status/1151180013909114881?s=20) to the documentation

### CODE REVIEW

**Comment by nunomaduro** [comment]
@caneco Maybe we can put the real assets here?

**Comment by rahman95** [comment]
@caneco If you give me a link to the asset, I can update this PR. Thanks

**Comment by caneco** [comment]
@rahman95 sorry to push yours aside but I've created another PR with a "pixel perfect" version of the logo, and with right colours, and a refreshed preview window 😊

**Comment by olivernybroe** [comment]
Thanks for doing this @rahman95, glad to see how fast you responded after the tweet! 😄 
But we will go with @caneco PR as he created the logo.

**Pull request closed without merging**
