### PR TITLE
Insight on phpinsights

### PR DESCRIPTION
**Pull request by szepeviktor**
Was #49

### CODE REVIEW

**Comment by nunomaduro** [comment]
Let's keep this Pull Request on hold while we waiting for someone to develop the status code.

**Comment by szepeviktor** [comment]
Do you plan to improve the code quality over time?

**Comment by nunomaduro** [comment]
@szepeviktor Sure. 🤗

**Comment by Jibbarth** [comment]
Stay tuned  => #67 :champagne:

**Comment by thenabeel** [comment]
Status code PR is merged.
So this PR can also be merged now.

**Comment by szepeviktor** [comment]
We have 2 problems: it always exits with OK, out code needs improvement.

**Comment by nunomaduro** [comment]
@szepeviktor Buddy, can you adjust the PR with min levels?

**Comment by szepeviktor** [comment]
Please tell me the values.

`--min-quality=0 --min-complexity=0 --min-architecture=0 --min-style=0`

**Comment by nunomaduro** [comment]
```
--min-quality=85.9 --min-complexity=73.7 --min-architecture=77.3 --min-style=89.1
```

**Comment by szepeviktor** [comment]
Done.

**Comment by nunomaduro** [comment]
Thanks buddy!

**Pull request merged**
