### PR TITLE
dockerized

### PR DESCRIPTION
**Pull request by smokills**
Since not all projects can be updated to php 7.2, I've dockerized this package.

It would be interesting to create a stage in the CI pipeline and push the image on the docker hub

### CODE REVIEW

**Comment by nunomaduro** [comment]
Someone with experience with the stack involved in this pull request that can help validation this solution?

**Comment by nunomaduro** [comment]
Related to #68

**Comment by deleugpn** [comment]
Did you get this to actually wor AFAIK, insights doesn't work on Alpine. See https://github.com/nunomaduro/phpinsights/issues/43
Will test this out tomorrow

**Comment by deleugpn** [comment]
For some reason, this distribution of the Alpine image works fine. This would be pretty good for CI, indeed.

@nunomaduro Do you plan on publishing this as an official image into Docker Hub? That way, we could run Insights without installing it as a dependency of our projects. Like `docker run -v /my/project:/app -it nunomaduro/phpinsights:1.0`. 

If you plan on doing that, it would be nice to publish the image and write the documentation accordingly. If not, the documentation would have to be more driven into how to build your own copy of the image and run it.

**Comment by nunomaduro** [comment]
I will try to find to study this.

**Comment by smokills** [comment]
@deleugpn as you can see I've used the official PHP CLI docker image, so i guess that this does the magic happens :D

**Comment by nunomaduro** [comment]
@smokills Can you update the PR with documentation? We should probably babysit the users here.

**Comment by smokills** [comment]
@nunomaduro I'll do it right now :D

**Comment by smokills** [comment]
@nunomaduro I've updated the documentation. There is a placeholder `<dockerhub namespace/imagename>` in which you have to replace the name of the image that you'll push on the docker hub

**Comment by nunomaduro** [comment]
Here is the docker thing: https://hub.docker.com/r/nunomaduro/phpinsights.

**Comment by nunomaduro** [comment]
@smokills Can you test if it's working? 🤗

**Comment by deleugpn** [comment]
@nunomaduro you need to build and push the image to Docker Hub. You'll have to: 

- `docker login` and provide your Docker Hub credentials
- `cd /path/to/insights`
- `docker build -f docker/Dockerfile . -t nunomaduro/phpinsights:1.0.0` (or whatever version you want)
- After the build is done, `docker push -t nunomaduro/phpinsights:1.0.0`

If you don't want to decide version right now, you can simply not write any version at all (e.g. docker build -f docker/Dockerfile . -t nunomaduro/phpinsights`) and it will build the tag `latest`. You can then push the latest image and leave a warning on the docs saying it's in Beta or something and you'll start versioning the Docker image at a later time.

**Comment by smokills** [comment]
@nunomaduro as @deleugpn says, you need to push the image on the dockerhub. I suggest to implement this in the CI. I see that you are using travis. Here is the doc about it:

https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry

**Comment by nunomaduro** [comment]
@deleugpn Do I need to do this every new version?

**Comment by deleugpn** [comment]
@nunomaduro The link @smokills provided will let you automate this with Travis by having Travis push a new image for every commit on your behalf. For testing purpose, I find it easier to push the first image manually until you have time to set it up automatically.

**Comment by nunomaduro** [comment]
@smokills @deleugpn Can you test again? https://cloud.docker.com/u/nunomaduro/repository/docker/nunomaduro/phpinsights

**Comment by smokills** [comment]
@nunomaduro it worked for me :)

Schermata 2019-05-17 alle 21 41 27

Another thing is that is a good practice to tag the last builded image with the `latest` tag, so if anyone forgot to type it in, the command will pull the `latest` one, that is the default pulled by docker if no tag is provided

**Comment by nunomaduro** [comment]
How exactly how I `tag the last builded image with the latest tag`?

**Comment by smokills** [comment]
`docker tag nunomaduro/phpinsights:v1.2.0  nunomaduro/phpinsights:latest` and after that you have to push it to the registry, like the previous one

**Comment by nunomaduro** [comment]
Can we make this `docker run -it --rm -v /path/to/app:/app nunomaduro/phpinsights` better? Like without specifying the path? And just running on the current path?

**Comment by smokills** [comment]
I think that this is not possible, because this it's how docker works. With that command you are basically saying: pull `nunomaduro/phpinsights` image from the docker registry, mount the `/path/to/app` of your host into the `/app` path into the container (it's kind of a copy), with the flag `-it` you are saying that you want an "interactive shell" and with `--rm` you are saying that after the command terminate, docker will remove the container from your machine

**Comment by nunomaduro** [comment]
Thanks you both for helping on this. @smokills @deleugpn

**Pull request merged**
