### PR TITLE
Add option to set timeout

### PR DESCRIPTION
**Pull request by holymp2006**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Fixed tickets | #546 

Add config option to set timeout.

### CODE REVIEW

**Comment by cmgmyr** [comment]
Hi @holymp2006, this looks like a great addition! Can you please remove your `aabac89` commit and rebase from the current `master` branch? That change is no longer needed.

**Comment by holymp2006** [comment]
Hello @cmgmyr , reverted the `aabac89` commit and rebased from the current `master` branch.

**Comment by cmgmyr** [comment]
Thanks @holymp2006, it looks like we have some various failures from the test suite. Rebasing or pulling in `master` might fix them, or there might be other issues in the changed code. Please LMK if you need help going through any of the items.

**Comment by gemal** [comment]
can this be merged?

**Comment by cmgmyr** [comment]
I rebased off current `master`, and most of the failures seem to be around styling. I'll take a closer look shortly and we should be able to merge

**Comment by gemal** [comment]
image

**Comment by gemal** [comment]
Nice! All checks have passed...

**Comment by joelvh** [comment]
I'm experiencing timeouts for a while now and this is a great feature to help resolve that. When will this be released?

**Comment by joelvh** [comment]
Thank you @cmgmyr!

**Pull request merged**
