### PR TITLE
[Release] v2.0

### PR DESCRIPTION
**Pull request by Jibbarth**
| Q             | A
| ------------- | ---
| Release ?      | yes
| Version number ?  | 2.0.0
| Fixed tickets | #... 

Hello :wave: 

I think, as we don't have anymore deprecated dependencies (thanks to @50bhan), we can now release the v2.

I tried to gather all the PR from the past year, tell me if you want some rewording some phrases.

@nunomaduro I have one job request for you :innocent:  We dropped the travis-ci process, and I need to be sure before merging this that the docker image will build and publish when tag be done. 
To ensure that, can you add your docker username and docker password in the Github Secret Section ? See below for the naming
<details>

image
</details>

Here is my latest Blackfire Performance comparison between v1.14 and this branch: https://blackfire.io/profiles/compare/1a9afee3-532e-418a-be00-c4eb2d42bf33/graph

### CODE REVIEW

**Comment by nunomaduro** [comment]
Going to give a spin on the master branch tonight, and give you the details you need by DM.

**Comment by 50bhan** [comment]
@Jibbarth 93% increasing the performance is crazy! Thank you for your great work!

P.S What do you think about adding a section in CHANGELOG for BC? (As we have some deprecated sniffs)

**Comment by Jibbarth** [comment]
@50bhan You are right ! Let'me study how it should be handle in http://keepachangelog.com :wink:

**Comment by nunomaduro** [comment]
@Jibbarth Can you tweet some of the improvements we will see on PHP Insights v2 please?

**Comment by guywarner** [comment]
Just bumping this on if there are any plans to move v2 forward and if there's anything I can do to help. It does seem that this PR is out of date on the change log from some of the recent merges.

**Comment by Jibbarth** [comment]
@guywarner Yes, you are right ! I will update this branch after merging #498 and #490 :wink:

**Comment by nunomaduro** [comment]
@Jibbarth Let me know if you need anything on my side - if not, fell free to release this version.

Don't forget is important to follow up this with a blog article explaining what's new, etc.

**Review by nunomaduro — APPROVED** [review]

**Pull request merged**
