### PR TITLE
Fix #73 : Add detail for ForbiddenGlobals Insight

### LINKED ISSUE #73: Details of globals accesses
Screen Shot 2019-05-16 at 14 37 44

And that's it, no more details, even with -v

Can you help with some method to see more details of it?

### PR DESCRIPTION
**Pull request by Morkhusz**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Fixed tickets | #73 

Here's how I managed to get issue #73 solved:
Created a method on Collector class to set Infos about globals usage, a method to get the infos and on Analyser class I've added those methods calls, also implemented HasDetails interface on ForbiddenGlobals class.
Can you guys provide me some enhancements tips?
Had some hard time at the codebase but I'm excited to change  anything to fit the need of this issue

### CODE REVIEW

**Comment by nunomaduro** [comment]
Yeah, ideally would be cool to receive this pull request without having changes on coding style.

**Comment by Morkhusz** [comment]
Yeah, sure guys!
Sorry about the coding style, I guess it was my IDE's plugin... I'll fix that and rebase cus' I forgot

**Comment by Morkhusz** [comment]
Just removed the 'increment' methods, those style changes and ran a rebase.
Anything you guys think that can be done I'll be happy with it!

**Comment by Morkhusz** [comment]
I'll be happy to do it!
Any insights on that? Cus' actually I couldn't find a test (unit) for the Analyser nor Collector classes so I guess it would be a feature test, right? So maybe I'll need a hand here

**Comment by olivernybroe** [comment]
Yeah, we don't actually have any tests for that part yet as far as I remember. If you are up for it, it would be awesome to have the test.

**Comment by nunomaduro** [comment]
@Morkhusz Let us know if you need any help on this.

**Comment by Morkhusz** [comment]
Sorry guys, I've been really busy at my job lately.
Maybe this weekend I'll be able to do those tests

**Comment by olivernybroe** [comment]
@Morkhusz Awesome! 
Totally understandable, just take your time :)

**Comment by Morkhusz** [comment]
Hello guys! I could only think about those test case... If someone have insights (got it? got it? xD) about what could be improved I'll do my best.

**Pull request merged**
