### PR TITLE
Make Contributions easier by having an online IDE (Gitpod)

### PR DESCRIPTION
**Pull request by meysholdt**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Fixed tickets | #... 

hi there 👋! 

thank you for helping to keep the code quality of many projects at high standards. 

I thought to help the community to contribute back their knowledge about best practices, I could be helpful to have an online IDE ([gitpod.io](gitpod.io)). That's a quick and convenient way for potential contributors to browse, modify and run the source code. Modifications can be submitted back to this project as PRs. Gitpod has full language support for PHP. In fact, it uses the same language server as VS Code.

To try, click here:
https://gitpod.io/#https://github.com/meysholdt/phpinsights

This will
1. launch a new workspace based on a docker image
2. git-clone this repository (GitHub OAuth needed)
3. run `composer install`.
4. If you enter `composer test` in the terminal, the tests will run and pass. 

This is how it looks like:

image

This PR:
- adds a config file to let Gitpod run `composer install` after opening a workspace.
- adds a link to the README to tell potential contributors about this possibility.

Disclosure: I work on Gitpod.

Let me know if this is something you find useful.

### CODE REVIEW

**Comment by meysholdt** [comment]
I've rebased the changes on `master` and now the Travis build passes. @nunomaduro, did you find time to look at this?

**Comment by nunomaduro** [comment]
Currently I am at some conferences marathon. Sorry. Seeing this next week.

**Comment by meysholdt** [comment]
Alright, thank you for your response. Enjoy the conferences!

**Comment by nunomaduro** [comment]
Holding this for the moment, sorry.

**Comment by meysholdt** [comment]
:-( 

what happened?

**Comment by nunomaduro** [comment]
Just holding this for the moment, I may consider adding this later.

**Pull request closed without merging**
