### PR TITLE
Add ComposerMustBeValid and ComposerLockMustBeFresh insights

### PR DESCRIPTION
**Pull request by Jibbarth**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Fixed tickets | #... 

Add new Insights about composer.

Example:

```
• [Architecture] Composer.json is not valid:
  composer.json: The property name is required
  composer.json: The property description is required
  composer.json: No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.

• [Architecture] The lock file is not up to date with the latest changes in composer.json:
  You may be getting outdated dependencies. Run update to update them.
```

### CODE REVIEW

**Comment by Jibbarth** [comment]
@olivernybroe I think this feature is already handled by https://github.com/nunomaduro/phpinsights/blob/master/src/Domain/Insights/ComposerMustContainName.php ?

**Comment by olivernybroe** [comment]
Oh yeah, totally forgot, sorry! :)

**Comment by Jibbarth** [comment]
> Could you add a few tests for this also?

I'll try :wink:

**Comment by Jibbarth** [comment]
@olivernybroe Tests added. Is it good for you ?

**Comment by Jibbarth** [comment]
Thanks a lot for the review @olivernybroe :+1:

**Pull request merged**
