### PR TITLE
Update our own minimums

### PR DESCRIPTION
**Pull request by szepeviktor**
min-complexity was missing

### CODE REVIEW

**Comment by szepeviktor** [comment]
See #203

**Comment by Jibbarth** [comment]
Yeah, `min-complexity` has been removed in [this commit](https://github.com/nunomaduro/phpinsights/commit/aac8ab28e74c8ae55a861615aa779e8191574d7d#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780) 

@nunomaduro remember why ?

**Comment by nunomaduro** [comment]
@Jibbarth Because it's hard to ship new features without decreasing that number.

**Comment by szepeviktor** [comment]
Oh! I see. Rapid pace.

**Comment by szepeviktor** [comment]
Sad news.

**Pull request closed without merging**
