### PR TITLE
Fresh new logo 💅

### PR DESCRIPTION
**Pull request by caneco**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Fixed tickets/pulss | #27, #220 |

Updated the introduction text in the README file, and added the official logo and artwork 🎉

### CODE REVIEW

**Comment by olivernybroe** [comment]
Just to be that annoying. 
But looks like the gif was rendered with a little bit of white border 😢 
image

**Comment by caneco** [comment]
@olivernybroe just added a version without background… that one it's for the subtle animation of the README file 😅

**Comment by olivernybroe** [comment]
@caneco Ah great! :) 
Just saw it, looks amazing!

If you have a SVG edition of it, then that would be cool to have in the arts folder also.
And one more annoying request... The colour codes you used, either just a comment in here or a readme file in the arts folder, so if we use the colours somewhere else, we use the right ones 👍

**Comment by caneco** [comment]
@olivernybroe you got your requested SVG version in #222 😄

**Pull request merged**
