### PR TITLE
Version 10 support

### PR DESCRIPTION
**Pull request by amirsadeghi1**

### CODE REVIEW

**Comment by colinmackinlay** [comment]
@amirsadeghi1 you might want to increase phpunit to include 10.0 as well?

**Comment by cmgmyr** [comment]
Thank you for your contribution. The Laravel 10 compatibility change has been made in #626

**Comment by rodrigopedra** [comment]
PHPInsigths still can't be installed on Laravel 10

```bash
~/code/playground $ php -v
PHP 8.1.16 (cli) (built: Mar 14 2023 00:00:00) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.16, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.16, Copyright (c), by Zend Technologies

~/code/playground $ laravel new l10

# output redacted for brevity

~/code/playground $ cd l10

~/code/playground/l10 $ php artisan --version
Laravel Framework 10.4.1

~/code/playground/l10 $ composer require nunomaduro/phpinsights --dev
./composer.json has been updated
Running composer update nunomaduro/phpinsights
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - nunomaduro/phpinsights[v2.4.0, ..., v2.5.0] require phploc/phploc ^5.0|^6.0|^7.0 -> satisfiable by phploc/phploc[5.0.0, 6.0.0, 6.0.1, 6.0.2, 7.0.0, 7.0.1, 7.0.2].
    - nunomaduro/phpinsights v2.8.0 requires cmgmyr/phploc ^8.0 -> satisfiable by cmgmyr/phploc[8.0.0, 8.0.1].
    - nunomaduro/phpinsights[v1.0.0, ..., v1.14.1] require php ^7.2 -> your php version (8.1.16) does not satisfy that requirement.
    - phploc/phploc 5.0.0 require php ^7.2 -> your php version (8.1.16) does not satisfy that requirement.
    - nunomaduro/phpinsights[v2.0.0, ..., v2.0.1] require psr/container ^1.0 -> found psr/container[1.0.0, 1.1.0, 1.1.1, 1.1.2] but the package is fixed to 2.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - nunomaduro/phpinsights[v2.1.0, ..., v2.3.0] require psr/simple-cache ^1.0 -> found psr/simple-cache[1.0.0, 1.0.1] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - nunomaduro/phpinsights[v2.6.0, ..., v2.7.0] require sebastian/diff ^4.0 -> found sebastian/diff[4.0.0, ..., 4.0.4] but the package is fixed to 5.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - phploc/phploc[6.0.0, ..., 6.0.2, 7.0.0, ..., 7.0.1] require php ^7.3 -> your php version (8.1.16) does not satisfy that requirement.
    - phploc/phploc 7.0.2 requires sebastian/cli-parser ^1.0 -> found sebastian/cli-parser[1.0.0, 1.0.1] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - cmgmyr/phploc[8.0.0, ..., 8.0.1] require sebastian/cli-parser ^1.0 -> found sebastian/cli-parser[1.0.0, 1.0.1] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires nunomaduro/phpinsights * -> satisfiable by nunomaduro/phpinsights[v1.0.0, ..., v1.14.1, v2.0.0, ..., v2.8.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require nunomaduro/phpinsights:*" to figure out if any version is installable, or "composer require nunomaduro/phpinsights:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

```

**Comment by cmgmyr** [comment]
This should be fixed now, please try again

**Comment by rodrigopedra** [comment]
Hey @cmgmyr thanks for the prompt response.

I don't know if you noticed this line in the output:

```bash
- nunomaduro/phpinsights v2.8.0 requires cmgmyr/phploc ...
```

As you can see, I tried with version 2.8.0. I have notifications turned on for new releases, as I am eager to get PHP Insights back on some projects.

I couldn't notice any new version greater than 2.8.0, which is what I tried yesterday before posting my comment. Furthermore, I apologize if I didn't make clear enough I was testing the recently released 2.8.0

https://packagist.org/packages/nunomaduro/phpinsights

Should I still try it again?

**Comment by cmgmyr** [comment]
I bumped a version in `cmgmyr/phploc` just a little while ago, but there wasn't any change needed for `phpinsights`, so a `composer update` should do it 👍

**Comment by rodrigopedra** [comment]
Just tried, and it worked. thanks! Not sure how it is different from yesterday's attempt, but thank you very much! 

Have a nice day =)

**Comment by rodrigopedra** [comment]
Oh! Now I see, I guess we were writing our comments at the same time. Thanks again =)

**Pull request closed without merging**
