### PR TITLE
add HTML formatter

### PR DESCRIPTION
**Pull request by Gummibeer**
| Q             | A
| ------------- | ---
| Bug fix?      |no
| New feature?  | yes
| Fixed tickets | #232 

This PR adds the ability to format the output as HTML and redirect it to a file, if wanted.

The result looks like this:
screencapture-localhost-63342-phpinsights-dashboard-html-2019-08-28-14_58_11

Under the hood Twig is used for templating. If wanted I can change this to be only a composer suggestion and have the user to install it by his own if he wants to use HTML formatter?

### CODE REVIEW

**Comment by nunomaduro** [comment]
So much potential in this pull request, we really need `twig` here?

**Comment by Gummibeer** [comment]
It makes it a lot easier than doing `'<strong>'.$metric.'</strong>'`. Without view files it would get a lot more code in the formatter and not this readable.
I understand your problem with it! And can refactor it out, but with it's easier and more readable.

**Comment by Gummibeer** [comment]
Another idea would be to use mustache, handlebars or any other JS template engine that could be loaded via CDN to get around the composer dependency but still don't render with string concatenation.

**Comment by olivernybroe** [comment]
I get why you choose to use twig, however it does add more dependencies. I think I might be fine with adding twig as it is much more needed when we add more advanced styling. 

Another suggestion would be to use the Json formatter and then parse the Json in JavaScript and handle it that way?

**Comment by Gummibeer** [comment]
@olivernybroe that was the idea in my last comment. It would only require a single HTML stub/template and no additional dependencies.
Even if most JS template engines I know lack real conditions, anything like twig filters and so on. Which would increase the view data preparation in PHP.
And using Vue is a bit overloaded I think!? For me the resulted HTML file should work out of the box **and** via simple `file://` link which is a problem for a lot of JS engines.
How about the optional twig dependency, let the user require it and in best case a small rework to support twig 1 & 2.
This won't install twig for everyone and everyone should find an installable version of twig if both major versions are supported!?

**Comment by olivernybroe** [comment]
We already have a lot of other dependencies that limit the user to the newest version and we have a workaround for dependency problems in the docs. 

I think I'll let @nunomaduro decide this. For me, I'll be okay with it.
I am not a fan of the idea that you have to composer install twig to use the HTML formatter, then I'll prefer the whole formatter to be a separate package that you just install in and then that package can have twig dependency.

**Comment by Gummibeer** [comment]
Anything I have to do here?

**Comment by olivernybroe** [comment]
@Gummibeer Sorry for the wait.

I think you should just add Twig in the `suggest` section of composer with a comment saying that it is needed for the html formatter. Then in the docs also add that you need to run `composer require...`. 

With those changes and the travis passing I think it's ready for the merging and then we can always change it later on.

**Comment by Gummibeer** [comment]
Ok, will do so.

**Comment by Gummibeer** [comment]
@olivernybroe should be fine now.

**Comment by olivernybroe** [comment]
@Gummibeer Looks great. Just need the test to pass then.

You can run `composer test` locally, so you don't have to wait for travis-ci.

One of the errors, you need to silence in the phpstan file, just like we did with the json formatter.
https://github.com/nunomaduro/phpinsights/blob/5d011f0549ba309c2405a42cdf7eb4b18d0fbe56/phpstan.neon.dist#L26

The other ones are stuff you need to program around  😃

**Comment by Gummibeer** [comment]
@olivernybroe just as an idea/hint: atm its' nearly impossible to find the thing that has to be fixed because of tons of errors (in phpinsights) that are accepted. And it's also not a great feeling that I'm responsible to fix this single issue that made the analyser switch from green to red if there is a list of hundreds of issues that's ok to be there.

**Comment by olivernybroe** [comment]
@Gummibeer Hmm, I get you, do you have any solution for it?

**Comment by Gummibeer** [comment]
Fix them 🤪😅
Or ignore them like phpstan. But selective ignore wasn't possible for phpinsights?

**Comment by olivernybroe** [comment]
Some of them should prob. be ignored, some should be fixed :) 

We have the feature to silence a specific error per file, but we need features for silence based on message and per folder. 

You are more than welcome to start fixing them! ♥️

**Comment by nunomaduro** [comment]
I don't think so. I think he have done a great job. By on the design we do way better.

**Comment by Gummibeer** [comment]
@nunomaduro do you have any example/layout? I can also use CDN tailwind. But I would like to don't include any SASS/JS in the package itself just for a formatter output style!?
And isn't this formatter meant for a fast and easy to read output? Everyone who want's to show this with his company branding or whatever can use the JSON formatter and display it.

**Comment by Gummibeer** [comment]
Nope, I even wouldn't say that I have frontend skills. :D

**Comment by nunomaduro** [comment]
Can you make a tweet asking for a help on the designer in this issue? If you don't want, I can do it.

**Comment by Gummibeer** [comment]
https://twitter.com/devgummibeer/status/1176795122538819587

**Comment by dmitryuk** [comment]
Any updates about the issue?

**Comment by olivernybroe** [comment]
@dmitryuk Still stuck on the need for a beautiful design for it unfortunately.

**Comment by dmitryuk** [comment]
@olivernybroe I will try to help us with a designer, but could you shortly describe what do you want to change in the current implementation?

**Comment by olivernybroe** [comment]
@dmitryuk I suck at designing, so not the best at coming with suggestions for this :) 
Maybe @nunomaduro  has some ideas?

**Comment by emjayess** [comment]
Cc: @feline-blue > heya Lauren this potential sweet feature needs a little injection of vanilla (no css kit dependency) css design! Whaddaya think?

**Comment by dmitryuk** [comment]
Good work!

**Comment by squpshift** [comment]
Hey, this appears to have been reverted. Why? :(

https://github.com/nunomaduro/phpinsights/commit/5e84dab8d7ba6fbf698fe606e71787cffce6807e

**Comment by gemal** [comment]
Any comment on why the HTML format was removed? Was there a problem?

**Comment by ArielMejiaDev** [comment]
Could anyone please tell me why this option has been removed? dependencies?

**Pull request merged**
