### PR TITLE
Feature/composer version check

### PR DESCRIPTION
**Pull request by akosglue**
| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| Fixed tickets | #...

### CODE REVIEW

**Comment by akosglue** [comment]
I opened this PR accidentally here instead of my fork before it is ready. However it will target #417

**Comment by 50bhan** [comment]
@akosglue Thank you for your work! Just as a comment here, could you please change your PR and limit it to the necessary changes for this PR? Because I can see this PR is mixed up with another two PRs.

**Comment by akosglue** [comment]
@50bhan if you look at 'Files changed' now, you seen only those 4 files that are related to this PR.
(2 fixtures, 1 test, 1 domain class)
Is it what you mean?
(the rest of the automatic checks will follow)

**Comment by 50bhan** [comment]
@akosglue Yes, this is exactly what I meant! Thanks.

**Comment by akosglue** [comment]
@50bhan would you be so kind as to look at these 2 failing checks? how is this related? I don't see it directly.

**Comment by 50bhan** [comment]
@akosglue Of course! I believe these failures are related to some dependency issues (as we have some problematic dependencies right now). So, I think I've fixed them already and made a PR for it (#477). We can merge that one first and then you can rebase and the CI failures might be fixed!

**Comment by 50bhan** [comment]
@akosglue The #478 PR has been merged and the problem with the CI failure does not exist anymore. You can rebase now and the tests will pass.

**Comment by akosglue** [comment]
@50bhan indeed, it worked.

**Review by Jibbarth — APPROVED** [review]
It's a great improvement :tada: 

Thank you @akosglue :+1:

**Pull request merged**
