### PR TITLE
Fixes #553 adds dont-exclude-tests option to allow analyse of tests folders

### LINKED ISSUE #553: Make phpinsights check tests directory
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | 1.14 ... 2.0

phpinsights ignores `tests/` directory.

Documentation states that by default it should exclude only `vendor`, `node_modules` and `bower_components`.

I agree that fixing issues in tests can be cumbersome. But phpinsights helps keeping same code style for all tracked files and tests aren't exclusion.
Currently I can run phpinsights with explicit check of `tests` folder but:
- that's unexpected behavior (found when my teammate added obviously bad code in it's PR and pipelines were not failed)
- hards manual use of phpinsights - you need to keep that in mind and manually run phpinsights multiple times (if there are not tools)
- pipelines needs to run more steps (that can be confusing).

Can we remove exclusion of `tests` or make it configurable with default set to true (excluded) ?

I'll create a PR if any of above is acceptable.

```yaml
# phpinsights.php
return [

    'preset' => 'default',

    'requirements' => [
        'min-architecture' => 100,
        'min-quality'      => 100,
        'min-complexity'   => 85,
        'min-style'        => 100,
    ],

    'exclude' => [
        'resources/',
        'storage/',
    ],
];
```

### PR DESCRIPTION
**Pull request by alexmakii**
Added dont_exclude_tests config
- Added config option "dont_exclude_tests"
- Added cli option "--dont-exclude-tests"
Small refactor of LocalFilesRepository
- Removed hardcoded list of files for exclusion
- Removed explicit exclussion of files by name, are already excluded by path
Added docs & updated tests

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Fixed tickets | #553

### CODE REVIEW

**Comment by alexmakii** [comment]
@JustSteveKing Can I do anything else to make this PR merged ?

This feature doesn't add breaking changes.

**Comment by JustSteveKing** [comment]
@alexmakii just running actions, will merge if all good!

**Comment by JustSteveKing** [comment]
@alexmakii this seems to have introduced a failing test, as soon as this is passing I would be happy to merge this in - it's been quite a requested feature!

**Comment by cmgmyr** [comment]
Closing until tests and conflicts are resolved

**Pull request closed without merging**
